CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES public.roles(id),
    cnic VARCHAR UNIQUE NOT NULL,
    full_name VARCHAR NOT NULL,
    contact_number VARCHAR,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.institutes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliation_no VARCHAR UNIQUE,
    name VARCHAR NOT NULL,
    head_user_id UUID REFERENCES public.user_profiles(id),
    address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.exam_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    location TEXT NOT NULL,
    capacity INT
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    normal_fee_date DATE NOT NULL,
    late_fee_date DATE NOT NULL,
    double_fee_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.degrees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    base_fee DECIMAL NOT NULL,
    min_age INT
);

CREATE TABLE IF NOT EXISTS public.subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS public.degree_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree_id BIGINT REFERENCES public.degrees(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    is_compulsory BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.students (
    id UUID PRIMARY KEY REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    father_name VARCHAR NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR NOT NULL,
    b_form_cnic VARCHAR UNIQUE NOT NULL,
    permanent_address TEXT NOT NULL,
    profile_image_url TEXT
);

CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.students(id),
    session_id BIGINT REFERENCES public.sessions(id),
    degree_id BIGINT REFERENCES public.degrees(id),
    institute_id BIGINT REFERENCES public.institutes(id),
    exam_center_id BIGINT REFERENCES public.exam_centers(id),
    enrollment_type VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    assigned_roll_no VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS public.enrollment_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES public.subjects(id),
    marks_obtained INT DEFAULT NULL,
    status VARCHAR DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE,
    total_marks INT,
    obtained_marks INT,
    percentage DECIMAL,
    grade VARCHAR,
    status VARCHAR, 
    is_published BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.challans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institute_id BIGINT REFERENCES public.institutes(id),
    student_id UUID REFERENCES public.students(id),
    amount DECIMAL NOT NULL,
    psid VARCHAR UNIQUE,
    status VARCHAR DEFAULT 'UNPAID',
    receipt_url TEXT
);

CREATE TABLE IF NOT EXISTS public.challan_enrollments (
    challan_id BIGINT REFERENCES public.challans(id) ON DELETE CASCADE,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE,
    PRIMARY KEY (challan_id, enrollment_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR NOT NULL,
    record_id VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    performed_by UUID REFERENCES auth.users(id),
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION log_audit_event()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, performed_by, new_data)
        VALUES (TG_TABLE_NAME, NEW.id::VARCHAR, 'INSERT', auth.uid(), to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, performed_by, old_data, new_data)
        VALUES (TG_TABLE_NAME, NEW.id::VARCHAR, 'UPDATE', auth.uid(), to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, performed_by, old_data)
        VALUES (TG_TABLE_NAME, OLD.id::VARCHAR, 'DELETE', auth.uid(), to_jsonb(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
