-- Add new columns to sessions
ALTER TABLE public.sessions 
  ADD COLUMN IF NOT EXISTS year INT,
  ADD COLUMN IF NOT EXISTS ad_date DATE,
  ADD COLUMN IF NOT EXISTS islamic_date VARCHAR(4),
  ADD COLUMN IF NOT EXISTS admission_open_date DATE;

-- Remove global fee dates from sessions as they are now per-course
ALTER TABLE public.sessions 
  DROP COLUMN IF EXISTS normal_fee_date,
  DROP COLUMN IF EXISTS late_fee_date,
  DROP COLUMN IF EXISTS double_fee_date;

-- Add mandatory electives count to degrees
ALTER TABLE public.degrees
  ADD COLUMN IF NOT EXISTS mandatory_electives_count INT DEFAULT 0;

-- Drop old degree_subjects if we are moving subjects to be per-session-course
-- Or keep it as a template, but the prompt says "admin will add elective subjects during session creation".
-- So the actual active subjects and marks are per session-course.
-- Let's create session_degrees first.

CREATE TABLE IF NOT EXISTS public.session_degrees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE,
    degree_id BIGINT REFERENCES public.degrees(id) ON DELETE CASCADE,
    base_fee DECIMAL NOT NULL,
    single_fee_deadline DATE NOT NULL,
    double_fee_deadline DATE NOT NULL,
    triple_fee_deadline DATE NOT NULL,
    UNIQUE(session_id, degree_id)
);

-- Now session_degree_subjects
CREATE TABLE IF NOT EXISTS public.session_degree_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_degree_id BIGINT REFERENCES public.session_degrees(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    is_compulsory BOOLEAN DEFAULT true,
    total_marks INT NOT NULL DEFAULT 100,
    UNIQUE(session_degree_id, subject_id)
);

-- Create a function to update UNPAID challans when a session_degree deadline changes
CREATE OR REPLACE FUNCTION update_unpaid_challans_on_deadline_change()
RETURNS TRIGGER AS $$
BEGIN
    -- This function will be triggered when single/double/triple fee deadlines are updated
    -- We need to find all UNPAID challans for enrollments belonging to this session_degree
    
    -- Actually, Challan calculation is complex (depends on current date).
    -- If the admin extends the deadline, a challan that was generated yesterday might now be 
    -- eligible for a lower fee.
    -- However, it's safer to recalculate dynamically or run an update script.
    -- For now, we will leave this as a placeholder or implement a basic recalculation logic.
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_session_degree_deadline_update
AFTER UPDATE OF single_fee_deadline, double_fee_deadline, triple_fee_deadline ON public.session_degrees
FOR EACH ROW EXECUTE FUNCTION update_unpaid_challans_on_deadline_change();
